"""create_initial_tables

Revision ID: 6de68b22c49e
Revises: 
Create Date: 2026-09-29 13:46:29.815814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de68b22c49e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_category',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_index(op.f('ix_t_category_category_id'), 't_category', ['category_id'], unique=False)
    op.create_table('t_user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_t_user_email'), 't_user', ['email'], unique=True)
    op.create_index(op.f('ix_t_user_user_id'), 't_user', ['user_id'], unique=False)
    op.create_table('t_recurring',
    sa.Column('recurring_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('INCOME', 'EXPENSE', name='recurring_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_method', sa.Enum('CASH', 'TRANSFER', name='recurring_method_enum'), nullable=False),
    sa.Column('account', sa.String(length=50), nullable=True),
    sa.Column('account_owner', sa.String(length=100), nullable=True),
    sa.Column('interval', sa.String(length=10), nullable=True),
    sa.Column('next_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['t_category.category_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recurring_id')
    )
    op.create_index(op.f('ix_t_recurring_recurring_id'), 't_recurring', ['recurring_id'], unique=False)
    op.create_table('t_transaction',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('INCOME', 'EXPENSE', name='transaction_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_method', sa.Enum('CASH', 'TRANSFER', name='transaction_method_enum'), nullable=False),
    sa.Column('account', sa.String(length=50), nullable=True),
    sa.Column('account_owner', sa.String(length=100), nullable=True),
    sa.Column('transaction_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['t_category.category_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_t_transaction_transaction_id'), 't_transaction', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_transaction_transaction_id'), table_name='t_transaction')
    op.drop_table('t_transaction')
    op.drop_index(op.f('ix_t_recurring_recurring_id'), table_name='t_recurring')
    op.drop_table('t_recurring')
    op.drop_index(op.f('ix_t_user_user_id'), table_name='t_user')
    op.drop_index(op.f('ix_t_user_email'), table_name='t_user')
    op.drop_table('t_user')
    op.drop_index(op.f('ix_t_category_category_id'), table_name='t_category')
    op.drop_table('t_category')
    # ### end Alembic commands ###
